AllCops:
  NewCops: enable
  Exclude:
    - "bin/**/*"
    - "vendor/**/*"
    - "config/**/*"
    - "db/migrate/*"
    - "db/schema.rb"

Style/AsciiComments:
  Enabled: true
Style/Documentation:
  Enabled: false

Lint/EmptyConditionalBody:
  Enabled: true

Lint/UselessAssignment:
  Enabled: true

Style/ClassAndModuleChildren:
  Enabled: false
