language: ruby
rvm:
  - 3.2.0

services:
  - postgresql

before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database rails_base_test;' -U postgres
  - bin/rails db:migrate RAILS_ENV=test

script:
  - bundle exec rails test

notifications:
  email: false
