language: ruby
rvm:
  - 3.3.0

services:
  - postgresql

env:
  global:
    - RAILS_ENV=test

before_install:
  - gem update --system
  - gem install bundler

before_script:
  - psql -c 'create database rails_base_test;' -U postgres
  - bin/rails db:migrate

script:
  - bundle exec rails test

notifications:
  email: false
