default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV['DB_USERNAME'] || 'cawell' %>
  password: <%= ENV['DB_PASSWORD'] || 'cawell123' %>
  host: <%= ENV['DB_HOST'] || 'localhost' %>
  port: <%= ENV['DB_PORT'] || 5432 %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rails_base_development

test:
  <<: *default
  database: rails_base_test

production:
  <<: *default
  database: rails_base_production
  username: rails_base
  password: <%= ENV["RAILS_BASE_DATABASE_PASSWORD"] %>
